### ISSUE TITLE
`timedout` when `options.timeout` is not set

### ISSUE THREAD

**Issue by eight04** [Ivordir/YALPS#3]
The model:
```js
{
  direction: 'maximize',
  objective: 'p1',
  constraints: {
    p1: { min: 0 },
    p2: { min: 2704 },
    p3: { min: 4221 },
    p4: { min: 0 },
    cost: { max: 11004 }
  },
  variables: {
    s1: { cost: 10, p1: 19, p2: 6, p3: 6 },
    s2: { cost: 10, p2: 24, p3: 6 },
    s3: { cost: 10, p2: 6, p3: 26 },
    s4: { cost: 10, p1: 31 },
    s5: { cost: 15, p1: 31, p2: 8, p3: 8 },
    s6: { cost: 15, p2: 36, p3: 8 },
    s7: { cost: 15, p2: 8, p3: 39 },
    s8: { cost: 15, p1: 46 },
    s9: { cost: 20, p1: 46, p2: 8, p3: 8 },
    s10: { cost: 20, p1: 8, p2: 51 },
    s11: { cost: 20, p1: 8, p3: 55 },
    s12: { cost: 20, p1: 61 }
  },
  integers: [
    's1',  's2',  's3',
    's4',  's5',  's6',
    's7',  's8',  's9',
    's10', 's11', 's12'
  ]
}
```

**Comment by Ivordir** [comment]
The solver can also time out due to `maxIterations`. 

> ```typescript
> /**
>  * This option applies to integer problems only.
>  * It determines the maximum number of iterations for the main branch and cut algorithm.
>  * It can be used alongside or instead of `timeout` to prevent the solver from taking too long.
>  * The default value is `32768`.
>  */
> maxIterations?: number
> ```

I will make the doc comments and README more clear.

For some reason, YALPS isn't able to handle your model particularly well, and it takes `9407742` branch and cut iterations to solve with tolerance=0.

**Comment by Ivordir** [comment]
Updated the documentation, so it should hopefully be clearer now.
